#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ahorcado.Droid.Resource", IsApplication=true)]

namespace Ahorcado.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ahorcado0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ahorcado1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ahorcado2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ahorcado3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ahorcado4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ahorcado5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ahorcado6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ahorcado7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int game = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
